//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica03.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbonosTB
    {
        public int IdAbono { get; set; }
        public int IdCompra { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal MontoAbono { get; set; }
    
        public virtual PrincipalTB PrincipalTB { get; set; }
    }
}
