//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica03.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrincipalTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrincipalTB()
        {
            this.AbonosTB = new HashSet<AbonosTB>();
        }
    
        public int IdCompra { get; set; }
        public string Descripcion { get; set; }
        public decimal MontoTotal { get; set; }
        public decimal Saldo { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbonosTB> AbonosTB { get; set; }
    }
}
